"""transfers table

Revision ID: 203248640ec9
Revises: fa5e4a9b70d5
Create Date: 2021-05-14 13:49:44.598788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203248640ec9'
down_revision = 'fa5e4a9b70d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_date'), 'transfer', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_date'), table_name='transfer')
    op.drop_table('transfer')
    # ### end Alembic commands ###
