"""notes table

Revision ID: ba92c03ce104
Revises: 55571a35f79c
Create Date: 2021-05-17 08:59:09.366126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba92c03ce104'
down_revision = '55571a35f79c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('body', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'body')
    # ### end Alembic commands ###
